# Generated by Django 3.1.3 on 2020-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='id',
        ),
        migrations.AlterField(
            model_name='cluster',
            name='root',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
