# Generated by Django 3.1.3 on 2020-12-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_auto_20201122_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='dec',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='goodtime',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Clean exptime (s)'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ra',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='RA'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='root',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Cluster name'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='z',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Redshift'),
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsid', models.IntegerField(verbose_name='ObsID')),
                ('instrument', models.CharField(max_length=6, verbose_name='Detector')),
                ('detnam', models.CharField(max_length=15, verbose_name='Detector CCDs')),
                ('expgoodtime', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Expected length (s)')),
                ('goodtime', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Good time (s)')),
                ('badtime', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Bad time (s)')),
                ('pubdate', models.DateField(verbose_name='Public Date')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
        ),
    ]
